repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        description: Remove trailing whitespace.
      - id: end-of-file-fixer
        description: Ensure a single newline at the end of files.
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-yaml
        description: Validate YAML files.

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args:
          - "--strict"
          - "image_processor"
        always_run: true
        pass_filenames: false
        files: ^(face_detection|image_processor)/.*\.py$

  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: npx --no-install commitlint --edit .git/COMMIT_EDITMSG
        language: node
        stages: [commit-msg]
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length=88"]

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.9
    hooks:
      - id: pylint
        args:
          - "--output-format=colorized"
          - "--rcfile=.pylintrc"
          - "--disable=raw-checker-failed,bad-inline-option,locally-disabled,file-ignored,suppressed-message,useless-suppression,deprecated-pragma,use-symbolic-message-instead,E1101"
        files: ^(face_detection|image_processor)/.*\.py$
        exclude: ^\.cache
        fail_fast: false
        additional_dependencies:
          - astroid>=3.3.3
          - setuptools<81

  - repo: local
    hooks:
      - id: prettier
        name: prettier (JSON/YAML/Markdown)
        entry: npx prettier --write --ignore-unknown
        language: system
        types_or: [json, yaml, markdown]
        exclude: ^(venv|\.venv|env|dist|build|__pycache__|\.pytest_cache|node_modules)/
