# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
        description: Remove trailing whitespace.
      - id: end-of-file-fixer
        description: Ensure a single newline at the end of files.
      - id: check-added-large-files
        args: ["--maxkb=500"] # Warn if files larger than 500 KB are added.

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1 # Use the latest stable version
    hooks:
      - id: flake8
        args: ["--max-line-length=88"] # Adjust based on your style guide
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: ["--strict"]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length=88"]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args:
          - "--output-format=colorized"
          - "disable=raw-checker-failed,
            bad-inline-option,
            locally-disabled,
            file-ignored,
            suppressed-message,
            useless-suppression,
            deprecated-pragma,
            use-symbolic-message-instead,
            use-implicit-booleaness-not-comparison-to-string,
            use-implicit-booleaness-not-comparison-to-zero,
            E1101"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: ["-r", "."]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        description: Validate YAML files.

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--write"]
        files: \.(json|md|yml|yaml)$
