name: Python application
#description: 'Check commits with linters, unit and e2e tests'

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        version: [1]

    steps:
      - name: Default directory
        run: |
          echo "CurrentDirectory=$(pwd)" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install opencv-python-headless

      - name: Set up packages
        uses: nill2/gha/install-packages@main

      - name: Lint with flake8 and pylint
        uses: nill2/gha/lint@main

      - name: Set up MongoDB
        run: |
          docker run -d --name mongodb -p 27017:27017 mongo:latest
          sleep 10  # Wait for MongoDB to start
        timeout-minutes: 3

      - name: Test unit tests with unittest
        env:
          IS_TEST: "test"
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }} 
        run: |
          cd $CurrentDirectory
          python setuptstmongo.py
          python -m unittest discover -s tests

      #- name: Test e2e tests with pytest
      #  env:
      #    IS_TEST: "GHA"
      #    MONGO_HOST: ${{ secrets.MONGO_HOST }}
      #    FTP_USER: ${{ secrets.FTP_USER }}
      #    FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      #    AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      #    AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      #  run: |
      #    pytest './tests/test_core.py'
